name: build

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Log in to DigitalOcean
        run: doctl registry login --expiry-seconds 600

      - name: Build and deploy master image to DigitalOcean
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo "GITHUB_REF=${GITHUB_REF}, GIT_BRANCH=${ref}"
          docker buildx build --push \
            --platform linux/amd64 \
            -t registry.digitalocean.com/timiskhakovcr/podfinder:${ref} .
