name: build

on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and deploy master image to ghcr.io
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          echo "GITHUB_REF=${GITHUB_REF}, GIT_BRANCH=${ref}"
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
          docker buildx build --push \
            --platform linux/amd64 \
            -t ghcr.io/${USERNAME}/podfinder:${ref} .