name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - name: Test
        run: go test -v ./...
        env:
          GOFLAGS: "-mod=vendor"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
